AUGMENTATION: True
IMAGE_SIZE: [224, 224, 3] # as per VGG 16 model
BATCH_SIZE: 16
INCLUDE_TOP: False # FC layer
EPOCHS: 1
CLASSES: 2 # Normal or Adenomacarcinoma
WEIGHTS: imagenet # use pretrained model
LEARNING_RATE: 0.01